on:
  push:
    branches: ["main"]
    paths:
      - "./Containerfile"
  pull_request:
    branches: ["main"]
    paths:
      - "./Containerfile"
  workflow_dispatch:

jobs:
  build:
    name: Build EDA DE and push image to Quay.
    env:
      working-directory: .
    defaults:
      run:
        working-directory: ${{ env.working-directory }}/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build DE image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: eda-decision-env
          tags: latest
          containerfiles: ${{ env.working-directory }}/Containerfile
          context: ${{ env.working-directory }}

      - name: Push To quay.io
        id: push-x86
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: latest
          registry: quay.io/kubealex
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
